language: java
services:
  - docker

before_install:
  - docker build --target maven -t java -f Dockerfile.test .
  - docker build --target ui -t ui -f Dockerfile.test .

script:
  - docker run java
  - docker run -e CI=true ui npm run test