services:
  - docker

before_install:
  - docker build --target build-kafka-producer -t kafa_producer -f Dockerfile.test .
  - docker build --target build-kafka-consumer -t kafa_consumer -f Dockerfile.test .
  - docker build --target build-server -t server -f Dockerfile.test .
  - docker build --target build-ui -t ui -f Dockerfile.test .

script:
  - docker run kafka-producer
  - docker run kafka-consumer
  - docker run server
  - docker run -e CI=true ui npm run test