language: node_js
node_js:
  - 10
services:
  - docker

before_install:
  - docker build --target ui -t ui -f Dockerfile.test .

script:
  - npm run build

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-test"
  env: "Dockertest-env"
  bucket_name: "elasticbeanstalk-us-east-2-825873962152"
  bucket_path: "docker-test"
  on:
    branch: docker-aws-test
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

