sudo: required
services:
  - docker

before_install:
  - docker build --target build-kafka-producer -t kafa_producer .
  - docker build --target build-kafka-consumer -t kafa_consumer .
  - docker build --target build-server -t server .
  - docker build --target ui-final -t ui .

script:
  - docker run -e CI=true ui npm run test