FROM maven:3.8.1-jdk-8-slim as maven
ENV APP_HOME=/usr/src/app
WORKDIR $APP_HOME
COPY ./pom.xml ./pom.xml
COPY ./server/pom.xml ./server/pom.xml
COPY ./kafka-redis-consumer/pom.xml ./kafka-redis-consumer/pom.xml
COPY ./kafka-producer/pom.xml ./kafka-producer/pom.xml
COPY ./model/pom.xml ./model/pom.xml
RUN mvn dependency:go-offline -B
COPY . $APP_HOME
RUN mvn package

FROM openjdk:8-jre-alpine as java
ENV APP_HOME=/usr/src/app
WORKDIR $APP_HOME

FROM maven as kafka-producer
RUN mvn test

FROM java as kafka-consumer
RUN mvn test

FROM java as server
RUN mvn test

FROM node:10.8.0 as ui
ENV APP_HOME=/usr/src/app
WORKDIR $APP_HOME
COPY client .
RUN npm install
ARG configuration=production
RUN npm run test