apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "books-store.labels" . | nindent 4 }}
    app: {{ .Values.backend.service.selector }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.backend.deployment.replicaCount }}
  {{- end }}
  minReadySeconds: {{ .Values.backend.deployment.minReadySeconds }}
  strategy:
    type: {{ .Values.backend.deployment.strategy }}
    rollingUpdate:
      maxUnavailable: {{ .Values.backend.deployment.maxUnavailable }}
      maxSurge: {{ .Values.backend.deployment.maxSurge }}
  selector:
    matchLabels:
      app: {{ .Values.backend.deployment.name }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.backend.deployment.name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.backend.deployment.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.repository }}/{{ .Values.backend.deployment.image.name }}:{{ .Values.backend.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.deployment.image.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.deployment.containerPort }}
          env:
            - name: MONGODB_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: MONGODB_SERVER_URL
            - name: KAFKA_PRODUCER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: KAFKA_PRODUCER_URL
            - name: KAFKA_CONSUMER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configmap.name }}
                  key: KAFKA_CONSUMER_URL

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
