{{- if .Values.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.certificate.name }}
spec:
  secretName: {{ .Values.ingress.tls.certificate.secretName }}
  issuerRef:
    name: {{ .Values.ingress.tls.issuer.key.name }}
    kind: ClusterIssuer
  commonName: {{ .Values.ingress.tls.certificate.commonName }}
  dnsNames:
    {{- range .Values.ingress.tls.hosts }}
    - {{ . | quote }}
    {{- end }}
{{- end }}