apiVersion: v1
kind: Secret
metadata:
    namespace: {{ .Values.namespace }}
    name: {{ .Values.custom_mongo_express.secret.name }}
# Opaque - default type for key-value pairs
type: Opaque 
data:
    mongo-root-username: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=
